name: Auto Deploy Nuxt (SFTP)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build

      # Ito ang mag-aayos ng SSH Key mo na may Passphrase
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          known_hosts: "just-a-placeholder-value" # Kusa itong maa-update mamaya
          if_key_exists: replace

      # Ito ang mag-a-add ng Hostinger sa known_hosts para hindi mag-error
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.FTP_PORT }} ${{ secrets.FTP_SERVER }} >> ~/.ssh/known_hosts

      # Gagamit tayo ng simpleng rsync command para sa deployment
      - name: Deploy with Rsync
        run: |
          rsync -avz -e "ssh -p ${{ secrets.FTP_PORT }}" .output/ ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:/home/u782169281/domains/pink-dotterel-993276.hostingersite.com/projects/Office-Mangement-System---Front/.output/
